Migrate to go mod
mat/besticon pull request #44
Opened 2020-12-08 15:08 UTC by korbenclario

For easier development and using up-to-date tools, I've migrated this repo to `go modules`.

Please, review and tell me if there is something to discuss.

- Removed vendors with Gopkg, as now they will be cached separately by go mod
- Added some additional files in the`.gitignore` for developing in IDE and on iOS

2020-12-09 17:09 UTC, mat commented
Thank you @korbenclario for this PR and congratulations to your first PR ! 😃

I quickly tested this and it works great. Just one thing seems broken: the task that combines the `NOTICES` file from all dependencies: [`make update_notices_file`](https://github.com/mat/besticon/blob/master/Makefile#L113-L118) now creates an empty NOTICES file. This is using the `licensed` tool, configured in the [`.licensed.yml`](https://github.com/mat/besticon/blob/master/.licensed.yml). Could you have a brief look into this?

2020-12-09 17:10 UTC, mat requested changes
Thank you @korbenclario for this PR and congratulations to your first PR ! 😃

I quickly tested this and it works great. Just one thing seems broken: the task that combines the `NOTICES` file from all dependencies: [`make update_notices_file`](https://github.com/mat/besticon/blob/master/Makefile#L113-L118) now creates an empty NOTICES file. This is using the `licensed` tool, configured in the [`.licensed.yml`](https://github.com/mat/besticon/blob/master/.licensed.yml). Could you have a brief look into this?

2020-12-10 10:10 UTC, korbenclario commented on .gitignore
> +/.env
Thank you @mat!
I've removed .gitignore changes and updated `licensed.yml`, some changes in NOTICES occurred due to go mod usage, please check.

2020-12-10 18:00 UTC, mat commented on .gitignore
> +/.env
LGTM, thank you 👍

2020-12-10 18:00 UTC, mat approved these changes

2020-12-10 18:01 UTC, merged